# coding: utf-8
import sys

sys.path.append('.')

BROKER_HOST = "srv-4.yottos.com"
BROKER_PORT = 5672
BROKER_USER = "getmyad_site"
BROKER_PASSWORD = "123qwe"
BROKER_VHOST = "getmyad_site_celery"
# BROKER_VHOST = "getmyad_site_celery_test"
BROKER_CONNECTION_MAX_RETRIES = 0
CELERY_RESULT_BACKEND = "cache"
CELERY_CACHE_BACKEND = 'memcached://127.0.0.1:11211/'
CELERY_IMPORTS = ("getmyad.tasks.mail",)
CELERY_TASK_RESULT_EXPIRES = 7200
CELERYD_CONCURRENCY = 15
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = "Europe/Kiev"
CELERYD_TASK_SOFT_TIME_LIMIT = 7200
CELERYD_TASK_TIME_LIMIT = 7200
CELERY_QUEUE_HA_POLICY = 'all'
CELERYD_MAX_TASKS_PER_CHILD = 5
CELERYD_PREFETCH_MULTIPLIER = 1
